import type { WouldYouRatherPrompt } from './would-you-rather.types.js';

export const wouldYouRatherPrompts: WouldYouRatherPrompt[] = [
  { id: 'wyr-001', left: 'always wake up at sunrise', right: 'always stay up past midnight' },
  { id: 'wyr-002', left: 'give up coffee forever', right: 'give up tea forever' },
  { id: 'wyr-003', left: 'live by the beach', right: 'live in the mountains' },
  { id: 'wyr-004', left: 'have perfect memory', right: 'learn new skills twice as fast' },
  { id: 'wyr-005', left: 'travel only by train', right: 'travel only by boat' },
  { id: 'wyr-006', left: 'always be slightly early', right: 'always be slightly late' },
  { id: 'wyr-007', left: 'have a pause button for life', right: 'have a rewind button for life' },
  { id: 'wyr-008', left: 'eat sweet food only', right: 'eat savory food only' },
  { id: 'wyr-009', left: 'have your dream job', right: 'have unlimited vacation time' },
  { id: 'wyr-010', left: 'be able to speak every language', right: 'be able to play every instrument' },
  { id: 'wyr-011', left: 'lose your phone for a week', right: 'lose your wallet for a week' },
  { id: 'wyr-012', left: 'watch movies only', right: 'watch series only' },
  { id: 'wyr-013', left: 'always know the weather tomorrow', right: 'always know traffic before leaving' },
  { id: 'wyr-014', left: 'have a private chef', right: 'have a private driver' },
  { id: 'wyr-015', left: 'work four long days', right: 'work six short days' },
  { id: 'wyr-016', left: 'never have to clean again', right: 'never have to cook again' },
  { id: 'wyr-017', left: 'only text people', right: 'only call people' },
  { id: 'wyr-018', left: 'always wear shoes indoors', right: 'never wear shoes outdoors' },
  { id: 'wyr-019', left: 'read minds for 10 seconds', right: 'be invisible for 10 seconds' },
  { id: 'wyr-020', left: 'have breakfast for every meal', right: 'have dinner for every meal' },
  { id: 'wyr-021', left: 'win every board game', right: 'win every card game' },
  { id: 'wyr-022', left: 'be famous online', right: 'be famous in your city' },
  { id: 'wyr-023', left: 'have a treehouse office', right: 'have a houseboat office' },
  { id: 'wyr-024', left: 'never get a cold again', right: 'never get a headache again' },
  { id: 'wyr-025', left: 'always have perfect Wi-Fi', right: 'always have a full phone battery' },
  { id: 'wyr-026', left: 'lose your sense of taste for a month', right: 'lose your sense of smell for a month' },
  { id: 'wyr-027', left: 'go camping every month', right: 'take a city trip every month' },
  { id: 'wyr-028', left: 'have a giant library', right: 'have a giant game room' },
  { id: 'wyr-029', left: 'be the funniest person in the room', right: 'be the smartest person in the room' },
  { id: 'wyr-030', left: 'only use cash', right: 'only use cards' },
  { id: 'wyr-031', left: 'always get the front parking spot', right: 'always skip the line' },
  { id: 'wyr-032', left: 'have a backyard pool', right: 'have a home cinema' },
  { id: 'wyr-033', left: 'only listen to old favorites', right: 'only listen to new music' },
  { id: 'wyr-034', left: 'be able to teleport nearby', right: 'be able to fly slowly' },
  { id: 'wyr-035', left: 'never hear ads again', right: 'never see spam again' },
  { id: 'wyr-036', left: 'own one perfect outfit', right: 'own endless average outfits' },
  { id: 'wyr-037', left: 'have a tiny house in every country', right: 'have one huge dream house' },
  { id: 'wyr-038', left: 'always know the right gift', right: 'always know the right words' },
  { id: 'wyr-039', left: 'be great at public speaking', right: 'be great at negotiations' },
  { id: 'wyr-040', left: 'never do laundry again', right: 'never wash dishes again' },
  { id: 'wyr-041', left: 'play sports every day', right: 'play video games every day' },
  { id: 'wyr-042', left: 'have a pet dog', right: 'have a pet cat' },
  { id: 'wyr-043', left: 'live somewhere warm all year', right: 'live somewhere with all four seasons' },
  { id: 'wyr-044', left: 'be on a reality show', right: 'be in a game show' },
  { id: 'wyr-045', left: 'only eat homemade food', right: 'only eat restaurant food' },
  { id: 'wyr-046', left: 'always find exactly what you need', right: 'never lose anything again' },
  { id: 'wyr-047', left: 'have perfect posture', right: 'have perfect sleep' },
  { id: 'wyr-048', left: 'be able to draw well', right: 'be able to dance well' },
  { id: 'wyr-049', left: 'share a room with your best friend', right: 'live alone in a tiny apartment' },
  { id: 'wyr-050', left: 'go without social media for a year', right: 'go without streaming for a year' },
  { id: 'wyr-051', left: 'have every meal be spicy', right: 'have every meal be mild' },
  { id: 'wyr-052', left: 'always know what to wear', right: 'always know what to cook' },
  { id: 'wyr-053', left: 'have an extra weekend day', right: 'have an extra vacation month' },
  { id: 'wyr-054', left: 'only use your laptop', right: 'only use your phone' },
  { id: 'wyr-055', left: 'be great at chess', right: 'be great at poker' },
  { id: 'wyr-056', left: 'have a beautiful singing voice', right: 'have perfect rhythm' },
  { id: 'wyr-057', left: 'be able to cook any meal', right: 'be able to fix any appliance' },
  { id: 'wyr-058', left: 'always be calm', right: 'always be motivated' },
  { id: 'wyr-059', left: 'vacation in the snow', right: 'vacation in the desert' },
  { id: 'wyr-060', left: 'have free coffee forever', right: 'have free dessert forever' },
  { id: 'wyr-061', left: 'have a small group of close friends', right: 'know a huge number of people' },
  { id: 'wyr-062', left: 'always choose the movie', right: 'always choose the music' },
  { id: 'wyr-063', left: 'be the team captain', right: 'be the strategy expert' },
  { id: 'wyr-064', left: 'be able to nap anywhere', right: 'be able to focus anywhere' },
  { id: 'wyr-065', left: 'eat no sugar for a year', right: 'eat no fried food for a year' },
  { id: 'wyr-066', left: 'wear only blue', right: 'wear only black' },
  { id: 'wyr-067', left: 'always know the score of any game', right: 'always know the time in any city' },
  { id: 'wyr-068', left: 'have a home gym', right: 'have a home studio' },
  { id: 'wyr-069', left: 'only shop online', right: 'only shop in person' },
  { id: 'wyr-070', left: 'be able to run long distances', right: 'be able to lift very heavy things' },
  { id: 'wyr-071', left: 'have one amazing vacation a year', right: 'have many short trips a year' },
  { id: 'wyr-072', left: 'always know who is calling', right: 'always know who is at the door' },
  { id: 'wyr-073', left: 'have a room that cleans itself', right: 'have a fridge that refills itself' },
  { id: 'wyr-074', left: 'live with no winters', right: 'live with no summers' },
  { id: 'wyr-075', left: 'be able to read fast', right: 'be able to type fast' },
  { id: 'wyr-076', left: 'only play cooperative games', right: 'only play competitive games' },
  { id: 'wyr-077', left: 'be in a musical', right: 'be in an action movie' },
  { id: 'wyr-078', left: 'have breakfast delivered daily', right: 'have dinner delivered daily' },
  { id: 'wyr-079', left: 'always know where your keys are', right: 'always know where your charger is' },
  { id: 'wyr-080', left: 'only watch comedies', right: 'only watch thrillers' },
  { id: 'wyr-081', left: 'be able to snowboard', right: 'be able to surf' },
  { id: 'wyr-082', left: 'have a giant desk', right: 'have a giant bed' },
  { id: 'wyr-083', left: 'go a year without junk food', right: 'go a year without soda' },
  { id: 'wyr-084', left: 'be the planner of every trip', right: 'be the driver on every trip' },
  { id: 'wyr-085', left: 'have an indoor garden', right: 'have a rooftop terrace' },
  { id: 'wyr-086', left: 'only take stairs', right: 'only take elevators' },
  { id: 'wyr-087', left: 'always remember names', right: 'always remember faces' },
  { id: 'wyr-088', left: 'have your ideal weather every weekend', right: 'have your ideal weather on every vacation' },
  { id: 'wyr-089', left: 'be able to bake perfectly', right: 'be able to grill perfectly' },
  { id: 'wyr-090', left: 'do all errands in one trip', right: 'never wait in traffic again' },
  { id: 'wyr-091', left: 'have endless notebooks', right: 'have endless batteries' },
  { id: 'wyr-092', left: 'be the best at trivia', right: 'be the best at charades' },
  { id: 'wyr-093', left: 'always have clean shoes', right: 'always have wrinkle-free clothes' },
  { id: 'wyr-094', left: 'go to bed early forever', right: 'sleep in late forever' },
  { id: 'wyr-095', left: 'have every app perfectly organized', right: 'have every file perfectly organized' },
  { id: 'wyr-096', left: 'own a scooter', right: 'own a bicycle' },
  { id: 'wyr-097', left: 'always know the best route', right: 'always know the best restaurant' },
  { id: 'wyr-098', left: 'spend a year near the ocean', right: 'spend a year near a forest' },
  { id: 'wyr-099', left: 'have one giant monitor', right: 'have three smaller monitors' },
  { id: 'wyr-100', left: 'be able to juggle', right: 'be able to do magic tricks' },
  { id: 'wyr-101', left: 'only drink hot drinks', right: 'only drink cold drinks' },
  { id: 'wyr-102', left: 'have a silent keyboard', right: 'have silent doors' },
  { id: 'wyr-103', left: 'know every shortcut key', right: 'know every cooking shortcut' },
  { id: 'wyr-104', left: 'always catch green lights', right: 'always get the best seat' },
  { id: 'wyr-105', left: 'live without air conditioning', right: 'live without heating' },
  { id: 'wyr-106', left: 'have one favorite song forever', right: 'never hear the same song twice' },
  { id: 'wyr-107', left: 'be great at improvising', right: 'be great at planning' },
  { id: 'wyr-108', left: 'own a cabin', right: 'own a loft' },
  { id: 'wyr-109', left: 'always know if food is still good', right: 'always know if a battery still works' },
  { id: 'wyr-110', left: 'eat only crunchy snacks', right: 'eat only chewy snacks' },
  { id: 'wyr-111', left: 'have free gym access forever', right: 'have free movie tickets forever' },
  { id: 'wyr-112', left: 'be able to remember every book you read', right: 'be able to remember every conversation' },
  { id: 'wyr-113', left: 'only use dark mode', right: 'only use light mode' },
  { id: 'wyr-114', left: 'have a perfect poker face', right: 'always know when others are bluffing' },
  { id: 'wyr-115', left: 'always get amazing photos', right: 'always write amazing captions' },
  { id: 'wyr-116', left: 'have a meal named after you', right: 'have a street named after you' },
  { id: 'wyr-117', left: 'work from a cafe', right: 'work from a library' },
  { id: 'wyr-118', left: 'always have the right tool', right: 'always have the right advice' },
  { id: 'wyr-119', left: 'have a one-minute commute', right: 'have a four-day work week' },
  { id: 'wyr-120', left: 'be able to whistle perfectly', right: 'be able to snap perfectly' },
  { id: 'wyr-121', left: 'have every package arrive early', right: 'have every message answered quickly' },
  { id: 'wyr-122', left: 'eat pizza forever', right: 'eat burgers forever' },
  { id: 'wyr-123', left: 'only use paper books', right: 'only use ebooks' },
  { id: 'wyr-124', left: 'have a hidden room in your house', right: 'have a secret tunnel from your house' },
  { id: 'wyr-125', left: 'be able to fix any bug instantly', right: 'be able to design any UI instantly' },
  { id: 'wyr-126', left: 'always know when someone is joking', right: 'always know when someone is lying' },
  { id: 'wyr-127', left: 'have fresh bread every morning', right: 'have fresh fruit every morning' },
  { id: 'wyr-128', left: 'win every raffle', right: 'find money in old pockets regularly' },
  { id: 'wyr-129', left: 'go without music for a month', right: 'go without podcasts for a month' },
  { id: 'wyr-130', left: 'be the fastest typer in the room', right: 'be the fastest reader in the room' },
  { id: 'wyr-131', left: 'own a camper van', right: 'own a sailboat' },
  { id: 'wyr-132', left: 'always remember birthdays', right: 'always remember appointments' },
  { id: 'wyr-133', left: 'have a perfect laugh', right: 'have a perfect handshake' },
  { id: 'wyr-134', left: 'spend a month offline in nature', right: 'spend a month in a new city' },
  { id: 'wyr-135', left: 'be able to build furniture easily', right: 'be able to assemble gadgets easily' },
  { id: 'wyr-136', left: 'always choose the winning team', right: 'always choose the right stock later' },
  { id: 'wyr-137', left: 'have very fast reflexes', right: 'have very high patience' },
  { id: 'wyr-138', left: 'have one giant party a year', right: 'have many small gatherings a year' },
  { id: 'wyr-139', left: 'always get the exact food you want', right: 'always get the exact temperature you want' },
  { id: 'wyr-140', left: 'only wear sneakers', right: 'only wear boots' },
  { id: 'wyr-141', left: 'know the ending of every movie before watching', right: 'never know what genre a movie is before watching' },
  { id: 'wyr-142', left: 'be able to refill your energy instantly once a day', right: 'be able to remove stress instantly once a day' },
  { id: 'wyr-143', left: 'have a snack drawer at work', right: 'have a nap room at work' },
  { id: 'wyr-144', left: 'be able to remember every dream', right: 'never have a nightmare again' },
  { id: 'wyr-145', left: 'live in a place with amazing food', right: 'live in a place with amazing scenery' },
  { id: 'wyr-146', left: 'always make the right first impression', right: 'always make the right final decision' },
  { id: 'wyr-147', left: 'be known for being kind', right: 'be known for being brilliant' },
  { id: 'wyr-148', left: 'have a giant whiteboard wall', right: 'have a giant map wall' },
  { id: 'wyr-149', left: 'be amazing at escape rooms', right: 'be amazing at scavenger hunts' },
  { id: 'wyr-150', left: 'own an arcade machine', right: 'own a pinball machine' },
];
